**Phase 1: Comprehensive Data Cleaning, Categorical Standardization, and Range Validation Pipeline**

**Pipeline Overview:**
1. Patient Profile Data Ingestion & Missing Value Imputation
2. Date Formatting & Categorical Text Normalization
3. Physiological Range Validation (Patients)
4. Daily Tracking Data Ingestion & Clinical Cleaning
5. Blood Pressure Parsing (Systolic & Diastolic Split)
6. Vitals & Nutrition Range Validation (Tracking)
7. Final Dataset Export for Feature Engineering Phase

**1. Load Datasets into Google Colab Environment**

In [ ]:
# Load datasets
from google.colab import files
uploaded = files.upload()

Saving daily_tracking_expanded (1).csv to daily_tracking_expanded (1).csv
Saving patients_expanded.csv to patients_expanded.csv

**2. Import Required Libraries**

In [ ]:
import pandas as pd

**SECTION 1: PATIENTS DATASET PROCESSING**

**3. Load Patient Profile Dataset**

In [ ]:
df = pd.read_csv("/content/cleaned_patients.csv")

**4. Checking Missing Values**

In [ ]:
df.isnull()

,patient_id,name,age,gender,height_cm,weight_kg,medical_condition,disease_type,surgery_type,medical_history,...,current_medications,diet_preference,food_restrictions,activity_level,lifestyle_type,smoking_status,alcohol_consumption,existing_conditions,doctor_notes,registration_date
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,True,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1296,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1297,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1298,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,True,False,False
1299,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
df.isnull().sum()

patient_id               0
name                     0
age                      0
gender                   0
height_cm                0
weight_kg                0
medical_condition        0
disease_type             0
surgery_type           913
medical_history          0
allergies              185
current_medications      0
diet_preference          0
food_restrictions      214
activity_level           0
lifestyle_type           0
smoking_status           0
alcohol_consumption    376
existing_conditions    429
doctor_notes             0
registration_date        0
dtype: int64

**5. Handle Missing Categorical Values**

In [ ]:
df['surgery_type'] = df['surgery_type'].fillna('None')
df['allergies'] = df['allergies'].fillna('None')
df['food_restrictions'] = df['food_restrictions'].fillna('None')
df['alcohol_consumption'] = df['alcohol_consumption'].fillna('None')
df['existing_conditions'] = df['existing_conditions'].fillna('None')

**6. Verify Missing Values**

In [ ]:
df.isnull()

,patient_id,name,age,gender,height_cm,weight_kg,medical_condition,disease_type,surgery_type,medical_history,...,current_medications,diet_preference,food_restrictions,activity_level,lifestyle_type,smoking_status,alcohol_consumption,existing_conditions,doctor_notes,registration_date
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1296,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1297,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1298,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.isnull().sum()

patient_id             0
name                   0
age                    0
gender                 0
height_cm              0
weight_kg              0
medical_condition      0
disease_type           0
surgery_type           0
medical_history        0
allergies              0
current_medications    0
diet_preference        0
food_restrictions      0
activity_level         0
lifestyle_type         0
smoking_status         0
alcohol_consumption    0
existing_conditions    0
doctor_notes           0
registration_date      0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1300 non-null   object
 1   name                 1300 non-null   object
 2   age                  1300 non-null   int64
 3   gender               1300 non-null   object
 4   height_cm            1300 non-null   int64
 5   weight_kg            1300 non-null   float64
 6   medical_condition    1300 non-null   object
 7   disease_type         1300 non-null   object
 8   surgery_type         1300 non-null   object
 9   medical_history      1300 non-null   object
 10  allergies            1300 non-null   object
 11  current_medications  1300 non-null   object
 12  diet_preference      1300 non-null   object
 13  food_restrictions    1300 non-null   object
 14  activity_level       1300 non-null   object
 15  lifestyle_type       1300 non-null   object
 16  smoking_status       1300 non-null   object
 17  alcohol_consumption  1300 non-null   object
 18  existing_conditions  1300 non-null   object
 19  doctor_notes         1300 non-null   object
 20  registration_date    1300 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 213.4+ KB

**7. Standardize Date Formats**

In [ ]:
df['registration_date'] = pd.to_datetime(df['registration_date'], format = '%d-%m-%Y')
print("Data types converting after 'registration_date':")
df.info()
df.head()

Data types converting after 'registration_date':
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1300 non-null   object
 1   name                 1300 non-null   object
 2   age                  1300 non-null   int64
 3   gender               1300 non-null   object
 4   height_cm            1300 non-null   int64
 5   weight_kg            1300 non-null   float64
 6   medical_condition    1300 non-null   object
 7   disease_type         1300 non-null   object
 8   surgery_type         1300 non-null   object
 9   medical_history      1300 non-null   object
 10  allergies            1300 non-null   object
 11  current_medications  1300 non-null   object
 12  diet_preference      1300 non-null   object
 13  food_restrictions    1300 non-null   object
 14  activity_level       1300 non-null   object
 15  lifestyle_type       1300 non-null   object
 16  smoking_status       1300 non-null   object
 17  alcohol_consumption  1300 non-null   object
 18  existing_conditions  1300 non-null   object
 19  doctor_notes         1300 non-null   object
 20  registration_date    1300 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(17)
memory usage: 213.4+ KB

,patient_id,name,age,gender,height_cm,weight_kg,medical_condition,disease_type,surgery_type,medical_history,...,current_medications,diet_preference,food_restrictions,activity_level,lifestyle_type,smoking_status,alcohol_consumption,existing_conditions,doctor_notes,registration_date
0,Pat0001,Vivaan White,45,Male,175,89.5,Chronic Kidney Disease,Renal,Kidney Transplant,Underwent Treatment For Chronic Kidney Disease...,...,"Losartan, Epoetin Alfa, Sevelamer",Eggetarian,Low Sugar,Sedentary,Desk Job,Never,None,Pre-Diabetes,Stable condition. Annual review scheduled.,2025-05-09
1,Pat0002,Sanjay Smith,44,Male,184,84.1,Chronic Kidney Disease,Renal,Dialysis Access Surgery,Diagnosed 12 Years Ago,...,"Calcitriol, Losartan",Vegan,Low Sugar,Sedentary,Shift Work,Never,Occasional,"Varicose Veins, Sleep Apnea",Patient responding well to current treatment p...,2023-09-13
2,Pat0003,Myra Rahman,59,Female,171,69.2,Copd,Respiratory,None,Secondary Complications Observed,...,Fluticasone-Salmeterol,Vegan,None,Lightly Active,Homemaker,Never,Moderate,None,Blood work shows improvement. Continue current...,2025-01-28
3,Pat0004,Riya Wilson,41,Female,163,62.9,Chronic Kidney Disease,Renal,Dialysis Access Surgery,Secondary Complications Observed,...,"Calcitriol, Losartan, Furosemide",Eggetarian,Low Fat,Extremely Active,Field Work,Current - Heavy,Occasional,"Pre-Diabetes, Iron Deficiency",Patient responding well to current treatment p...,2025-04-01
4,Pat0005,Aadhya Desai,19,Female,161,45.0,Anemia,Hematological,None,Multiple Episodes Requiring Emergency Care,...,Vitamin B12,Non-Vegetarian,Low Sugar,Extremely Active,Retired,Never,Heavy,Varicose Veins,Patient non-compliant with medication schedule...,2024-03-25

**8. Standardise categorical values**

In [ ]:
categorical_col = df.select_dtypes(include=['object']).columns
Standardise_col = ['name','gender', 'medical_condition', 'disease_type',
       'surgery_type', 'medical_history', 'allergies', 'current_medications',
       'diet_preference', 'food_restrictions', 'activity_level',
       'lifestyle_type', 'smoking_status', 'alcohol_consumption',
       'existing_conditions']

for col in Standardise_col:
    if col in df.columns:
        df[col] = df[col].astype(str).str.title().str.strip()

print("Data types after categorical standardization:")
df.info()
df.head()

Data types after categorical standardization:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1300 non-null   object
 1   name                 1300 non-null   object
 2   age                  1300 non-null   int64
 3   gender               1300 non-null   object
 4   height_cm            1300 non-null   int64
 5   weight_kg            1300 non-null   float64
 6   medical_condition    1300 non-null   object
 7   disease_type         1300 non-null   object
 8   surgery_type         1300 non-null   object
 9   medical_history      1300 non-null   object
 10  allergies            1300 non-null   object
 11  current_medications  1300 non-null   object
 12  diet_preference      1300 non-null   object
 13  food_restrictions    1300 non-null   object
 14  activity_level       1300 non-null   object
 15  lifestyle_type       1300 non-null   object
 16  smoking_status       1300 non-null   object
 17  alcohol_consumption  1300 non-null   object
 18  existing_conditions  1300 non-null   object
 19  doctor_notes         1300 non-null   object
 20  registration_date    1300 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(17)
memory usage: 213.4+ KB

,patient_id,name,age,gender,height_cm,weight_kg,medical_condition,disease_type,surgery_type,medical_history,...,current_medications,diet_preference,food_restrictions,activity_level,lifestyle_type,smoking_status,alcohol_consumption,existing_conditions,doctor_notes,registration_date
0,Pat0001,Vivaan White,45,Male,175,89.5,Chronic Kidney Disease,Renal,Kidney Transplant,Underwent Treatment For Chronic Kidney Disease...,...,"Losartan, Epoetin Alfa, Sevelamer",Eggetarian,Low Sugar,Sedentary,Desk Job,Never,None,Pre-Diabetes,Stable condition. Annual review scheduled.,2025-05-09
1,Pat0002,Sanjay Smith,44,Male,184,84.1,Chronic Kidney Disease,Renal,Dialysis Access Surgery,Diagnosed 12 Years Ago,...,"Calcitriol, Losartan",Vegan,Low Sugar,Sedentary,Shift Work,Never,Occasional,"Varicose Veins, Sleep Apnea",Patient responding well to current treatment p...,2023-09-13
2,Pat0003,Myra Rahman,59,Female,171,69.2,Copd,Respiratory,None,Secondary Complications Observed,...,Fluticasone-Salmeterol,Vegan,None,Lightly Active,Homemaker,Never,Moderate,None,Blood work shows improvement. Continue current...,2025-01-28
3,Pat0004,Riya Wilson,41,Female,163,62.9,Chronic Kidney Disease,Renal,Dialysis Access Surgery,Secondary Complications Observed,...,"Calcitriol, Losartan, Furosemide",Eggetarian,Low Fat,Extremely Active,Field Work,Current - Heavy,Occasional,"Pre-Diabetes, Iron Deficiency",Patient responding well to current treatment p...,2025-04-01
4,Pat0005,Aadhya Desai,19,Female,161,45.0,Anemia,Hematological,None,Multiple Episodes Requiring Emergency Care,...,Vitamin B12,Non-Vegetarian,Low Sugar,Extremely Active,Retired,Never,Heavy,Varicose Veins,Patient non-compliant with medication schedule...,2024-03-25

**9. Validate realistic data ranges**

In [ ]:
print("\n------- Numerical data range validation -----\n")

# General check for all numerical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    print(f"Column: {col}")
    print(f"  Min: {df[col].min()}")
    print(f"  Max: {df[col].max()}")
    print(f"  Mean: {df[col].mean():.2f}")
    print(f"  Median: {df[col].median():.2f}")
    print("--------------------------------")

------- Numerical data range validation -----

Column: age
  Min: 18
  Max: 89
  Mean: 46.78
  Median: 46.00
--------------------------------
Column: height_cm
  Min: 141
  Max: 190
  Mean: 165.97
  Median: 165.00
--------------------------------
Column: weight_kg
  Min: 34.7
  Max: 133.8
  Mean: 72.56
  Median: 71.40
--------------------------------

In [ ]:
#Age validation
if ((df['age'] < 0) | (df['age'] > 100)).any():
  print("There are unrealistic age values in the dataset.")
else:
  print("All age values are realistic.")

#Height validation
if((df['height_cm'] < 0) | (df['height_cm'] > 200)).any():
  print("There are unrealistic height values in the dataset.")
else:
  print("All height values are realistic.")

#Weight validation
if((df['weight_kg'] < 0) | (df['weight_kg'] > 200)).any():
  print("There are unrealistic weight values in the dataset.")
else:
  print("All weight values are realistic.")
#

All age values are realistic.
All height values are realistic.
All weight values are realistic.

**10. Download the dataset**

In [ ]:
output_filename = "final_cleaned_patients.csv"
df.to_csv(output_filename, index=False)
files.download(output_filename)

**SECTION 2: DAILY TRACKING DATASET PROCESSING**

**1. Load Daily Tracking Dataset**

In [ ]:
df1 = pd.read_csv("/content/daily_tracking_expanded (1).csv")

**2. Checking Missing Values**

In [ ]:
df1.isnull()

,record_id,patient_id,date,weight_kg,meals_taken,meal_compliance,calorie_intake,protein_intake,carb_intake,fat_intake,...,pain_level,energy_level,mood_status,medication_taken,bowel_movement_status,blood_sugar_level,blood_pressure,heart_rate,doctor_visit,notes
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48116,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48117,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48118,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48119,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48120,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df1.isnull().sum()

record_id                    0
patient_id                   0
date                         0
weight_kg                  870
meals_taken                  0
meal_compliance              0
calorie_intake             862
protein_intake             956
carb_intake                913
fat_intake                 927
water_intake_liters          0
steps_count                529
exercise_done            10227
sleep_hours                687
symptoms                 12679
pain_level                   0
energy_level                 0
mood_status                  0
medication_taken             0
bowel_movement_status        0
blood_sugar_level          912
blood_pressure             519
heart_rate                 732
doctor_visit                 0
notes                    15410
dtype: int64

**3. Data Preprocessing and Feature Extraction for Daily Tracking**

**4. Handling & Verify Missing Values**

In [ ]:
import numpy as np

# Clean column names
df1.columns = df1.columns.str.strip().str.lower()

# Handle categorical columns
categorical_cols = ['exercise_done', 'symptoms', 'notes']

for col in categorical_cols:
    if col in df1.columns:
        df1[col] = df1[col].fillna('None')

# Handle blood pressure
if 'blood_pressure' in df1.columns:

    # Convert to string
    bp_split = df1['blood_pressure'].astype(str).str.split('/', expand=True)

    # Create systolic and diastolic columns
    df1['systolic_bp'] = pd.to_numeric(bp_split[0], errors='coerce')
    df1['diastolic_bp'] = pd.to_numeric(bp_split[1], errors='coerce')

    # Fill missing values with median
    df1['systolic_bp'] = df1['systolic_bp'].fillna(df1['systolic_bp'].median())
    df1['diastolic_bp'] = df1['diastolic_bp'].fillna(df1['diastolic_bp'].median())

    # Drop original column
    df1.drop(columns=['blood_pressure'], inplace=True)

# Numerical columns
numerical_cols = ['weight_kg', 'calorie_intake', 'protein_intake', 'carb_intake', 'fat_intake',
                  'steps_count', 'sleep_hours', 'blood_sugar_level', 'heart_rate']

# Convert columns to numeric safely
for col in numerical_cols:
    if col in df1.columns:
        df1[col] = pd.to_numeric(df1[col], errors='coerce')

        # Fill missing values with median
        df1[col] = df1[col].fillna(df1[col].median())

# Final null check
print("Remaining Null Values:")
print(df1.isnull().sum())

print("\nDataset Info:")
print(df1.info())

print("\nFirst 5 Rows:")
display(df1.head())

Remaining Null Values:
record_id                0
patient_id               0
date                     0
weight_kg                0
meals_taken              0
meal_compliance          0
calorie_intake           0
protein_intake           0
carb_intake              0
fat_intake               0
water_intake_liters      0
steps_count              0
exercise_done            0
sleep_hours              0
symptoms                 0
pain_level               0
energy_level             0
mood_status              0
medication_taken         0
bowel_movement_status    0
blood_sugar_level        0
heart_rate               0
doctor_visit             0
notes                    0
systolic_bp              0
diastolic_bp             0
dtype: int64

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48121 entries, 0 to 48120
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   record_id              48121 non-null  object
 1   patient_id             48121 non-null  object
 2   date                   48121 non-null  datetime64[ns]
 3   weight_kg              48121 non-null  float64
 4   meals_taken            48121 non-null  int64
 5   meal_compliance        48121 non-null  object
 6   calorie_intake         48121 non-null  float64
 7   protein_intake         48121 non-null  float64
 8   carb_intake            48121 non-null  float64
 9   fat_intake             48121 non-null  float64
 10  water_intake_liters    48121 non-null  float64
 11  steps_count            48121 non-null  float64
 12  exercise_done          48121 non-null  object
 13  sleep_hours            48121 non-null  float64
 14  symptoms               48121 non-null  object
 15  pain_level             48121 non-null  int64
 16  energy_level           48121 non-null  object
 17  mood_status            48121 non-null  object
 18  medication_taken       48121 non-null  object
 19  bowel_movement_status  48121 non-null  object
 20  blood_sugar_level      48121 non-null  float64
 21  heart_rate             48121 non-null  float64
 22  doctor_visit           48121 non-null  object
 23  notes                  48121 non-null  object
 24  systolic_bp            48121 non-null  float64
 25  diastolic_bp           48121 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(2), object(11)
memory usage: 9.5+ MB
None

First 5 Rows:

,record_id,patient_id,date,weight_kg,meals_taken,meal_compliance,calorie_intake,protein_intake,carb_intake,fat_intake,...,energy_level,mood_status,medication_taken,bowel_movement_status,blood_sugar_level,heart_rate,doctor_visit,notes,systolic_bp,diastolic_bp
0,Rec000001,Pat0001,2025-05-22,89.4,3,Full,2276.0,141.1,309.2,73.2,...,Moderate,Low,Yes,Normal,95.0,68.0,No,None,120.0,84.0
1,Rec000002,Pat0001,2025-05-23,90.0,3,Partial,1880.0,85.4,178.1,69.0,...,Very High,Low,Yes,Loose,95.0,73.0,No,None,132.0,66.0
2,Rec000003,Pat0001,2025-05-24,89.7,3,Partial,2081.8,66.1,190.0,61.4,...,Very Low,Good,Yes,Constipation,73.0,73.0,No,None,129.0,74.0
3,Rec000004,Pat0001,2025-05-25,89.7,2,Partial,1769.0,74.7,222.4,58.4,...,Moderate,Calm,Yes,Normal,107.0,69.0,No,None,102.0,74.0
4,Rec000005,Pat0001,2025-05-26,89.5,3,Full,2407.0,98.0,234.8,69.2,...,High,Good,Yes,Normal,92.0,88.0,No,Feeling Positive About Progress,108.0,77.0

**5. Validate datatypes**

In [ ]:
df1['date'] = pd.to_datetime(df1['date'], format = '%d-%m-%Y')
print("\n----- Data types ['date'] after date\n")
df1.info()
df1.head()

----- Data types ['date'] after date

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48121 entries, 0 to 48120
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   record_id              48121 non-null  object
 1   patient_id             48121 non-null  object
 2   date                   48121 non-null  datetime64[ns]
 3   weight_kg              48121 non-null  float64
 4   meals_taken            48121 non-null  int64
 5   meal_compliance        48121 non-null  object
 6   calorie_intake         48121 non-null  float64
 7   protein_intake         48121 non-null  float64
 8   carb_intake            48121 non-null  float64
 9   fat_intake             48121 non-null  float64
 10  water_intake_liters    48121 non-null  float64
 11  steps_count            48121 non-null  float64
 12  exercise_done          48121 non-null  object
 13  sleep_hours            48121 non-null  float64
 14  symptoms               48121 non-null  object
 15  pain_level             48121 non-null  int64
 16  energy_level           48121 non-null  object
 17  mood_status            48121 non-null  object
 18  medication_taken       48121 non-null  object
 19  bowel_movement_status  48121 non-null  object
 20  blood_sugar_level      48121 non-null  float64
 21  heart_rate             48121 non-null  float64
 22  doctor_visit           48121 non-null  object
 23  notes                  48121 non-null  object
 24  systolic_bp            48121 non-null  float64
 25  diastolic_bp           48121 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(2), object(11)
memory usage: 9.5+ MB

,record_id,patient_id,date,weight_kg,meals_taken,meal_compliance,calorie_intake,protein_intake,carb_intake,fat_intake,...,energy_level,mood_status,medication_taken,bowel_movement_status,blood_sugar_level,heart_rate,doctor_visit,notes,systolic_bp,diastolic_bp
0,Rec000001,Pat0001,2025-05-22,89.4,3,Full,2276.0,141.1,309.2,73.2,...,Moderate,Low,Yes,Normal,95.0,68.0,No,None,120.0,84.0
1,Rec000002,Pat0001,2025-05-23,90.0,3,Partial,1880.0,85.4,178.1,69.0,...,Very High,Low,Yes,Loose,95.0,73.0,No,None,132.0,66.0
2,Rec000003,Pat0001,2025-05-24,89.7,3,Partial,2081.8,66.1,190.0,61.4,...,Very Low,Good,Yes,Constipation,73.0,73.0,No,None,129.0,74.0
3,Rec000004,Pat0001,2025-05-25,89.7,2,Partial,1769.0,74.7,222.4,58.4,...,Moderate,Calm,Yes,Normal,107.0,69.0,No,None,102.0,74.0
4,Rec000005,Pat0001,2025-05-26,89.5,3,Full,2407.0,98.0,234.8,69.2,...,High,Good,Yes,Normal,92.0,88.0,No,Feeling Positive About Progress,108.0,77.0

**6. Standardise categorical values**

In [ ]:
categorical_col = df1.select_dtypes(include=['object']).columns
Standardise_col = ['record_id','patient_id', 'meal_compliance', 'exercise_done',
       'symptoms', 'energy_level', 'mood_status', 'medication_taken',
       'bowel_movement_status', 'blood_pressure', 'doctor_visit',
       'notes']

for col in Standardise_col:
    if col in df1.columns:
        df1[col] = df1[col].astype(str).str.title().str.strip()

print("Data types after categorical standardization:")
df1.info()
df1.head()

Data types after categorical standardization:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48121 entries, 0 to 48120
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   record_id              48121 non-null  object
 1   patient_id             48121 non-null  object
 2   date                   48121 non-null  datetime64[ns]
 3   weight_kg              48121 non-null  float64
 4   meals_taken            48121 non-null  int64
 5   meal_compliance        48121 non-null  object
 6   calorie_intake         48121 non-null  float64
 7   protein_intake         48121 non-null  float64
 8   carb_intake            48121 non-null  float64
 9   fat_intake             48121 non-null  float64
 10  water_intake_liters    48121 non-null  float64
 11  steps_count            48121 non-null  float64
 12  exercise_done          48121 non-null  object
 13  sleep_hours            48121 non-null  float64
 14  symptoms               48121 non-null  object
 15  pain_level             48121 non-null  int64
 16  energy_level           48121 non-null  object
 17  mood_status            48121 non-null  object
 18  medication_taken       48121 non-null  object
 19  bowel_movement_status  48121 non-null  object
 20  blood_sugar_level      48121 non-null  float64
 21  heart_rate             48121 non-null  float64
 22  doctor_visit           48121 non-null  object
 23  notes                  48121 non-null  object
 24  systolic_bp            48121 non-null  float64
 25  diastolic_bp           48121 non-null  float64
dtypes: datetime64[ns](1), float64(12), int64(2), object(11)
memory usage: 9.5+ MB

,record_id,patient_id,date,weight_kg,meals_taken,meal_compliance,calorie_intake,protein_intake,carb_intake,fat_intake,...,energy_level,mood_status,medication_taken,bowel_movement_status,blood_sugar_level,heart_rate,doctor_visit,notes,systolic_bp,diastolic_bp
0,Rec000001,Pat0001,2025-05-22,89.4,3,Full,2276.0,141.1,309.2,73.2,...,Moderate,Low,Yes,Normal,95.0,68.0,No,None,120.0,84.0
1,Rec000002,Pat0001,2025-05-23,90.0,3,Partial,1880.0,85.4,178.1,69.0,...,Very High,Low,Yes,Loose,95.0,73.0,No,None,132.0,66.0
2,Rec000003,Pat0001,2025-05-24,89.7,3,Partial,2081.8,66.1,190.0,61.4,...,Very Low,Good,Yes,Constipation,73.0,73.0,No,None,129.0,74.0
3,Rec000004,Pat0001,2025-05-25,89.7,2,Partial,1769.0,74.7,222.4,58.4,...,Moderate,Calm,Yes,Normal,107.0,69.0,No,None,102.0,74.0
4,Rec000005,Pat0001,2025-05-26,89.5,3,Full,2407.0,98.0,234.8,69.2,...,High,Good,Yes,Normal,92.0,88.0,No,Feeling Positive About Progress,108.0,77.0

**7. Validate realistic data ranges**

In [ ]:
print("\n------- Numerical data range validation -----\n")

# General check for all numerical columns
numerical_cols = df1.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_cols:
    print(f"Column: {col}")
    print(f"  Min: {df1[col].min()}")
    print(f"  Max: {df1[col].max()}")
    print(f"  Mean: {df1[col].mean():.2f}")
    print(f"  Median: {df1[col].median():.2f}")
    print("--------------------------------")

# Validate realistic data ranges
# Weight in kg: 2 - 120
df1 = df1[df1['weight_kg'].between(2, 300)]

# Calorie intake: 0 - 10000
df1 = df1[df1['calorie_intake'].between(0, 10000)]

# Protein intake: 0 - 500 grams
df1 = df1[df1['protein_intake'].between(0, 500)]

# Carbohydrate intake: 0 - 1000 grams
df1 = df1[df1['carb_intake'].between(0, 1000)]

# Fat intake: 0 - 500 grams
df1 = df1[df1['fat_intake'].between(0, 500)]

# Steps count: 0 - 100000
df1 = df1[df1['steps_count'].between(0, 100000)]

# Sleep hours: 0 - 24
df1 = df1[df1['sleep_hours'].between(0, 24)]

# Blood sugar level: 40 - 500 mg/dL
df1 = df1[df1['blood_sugar_level'].between(40, 500)]

# Heart rate: 30 - 220 bpm
df1 = df1[df1['heart_rate'].between(30, 220)]

# Systolic BP: 70 - 250
df1 = df1[df1['systolic_bp'].between(70, 250)]

# Diastolic BP: 40 - 150
df1 = df1[df1['diastolic_bp'].between(40, 150)]

# -----------------------------------
# Final dataset shape
# -----------------------------------

print("Dataset shape after validation:")
print(df1.shape)

print("\nRemaining Null Values:")
print(df1.isnull().sum())

------- Numerical data range validation -----

Column: weight_kg
  Min: 34.8
  Max: 133.1
  Mean: 71.09
  Median: 70.10
--------------------------------
Column: meals_taken
  Min: 2
  Max: 5
  Mean: 3.32
  Median: 3.00
--------------------------------
Column: calorie_intake
  Min: 800.0
  Max: 4000.0
  Mean: 2099.83
  Median: 2081.80
--------------------------------
Column: protein_intake
  Min: 27.9
  Max: 224.4
  Mean: 100.50
  Median: 98.00
--------------------------------
Column: carb_intake
  Min: 74.4
  Max: 515.6
  Mean: 225.16
  Median: 222.40
--------------------------------
Column: fat_intake
  Min: 19.2
  Max: 150.8
  Mean: 63.78
  Median: 62.50
--------------------------------
Column: water_intake_liters
  Min: 0.5
  Max: 5.0
  Mean: 2.65
  Median: 2.60
--------------------------------
Column: steps_count
  Min: 200.0
  Max: 25000.0
  Mean: 7861.77
  Median: 7538.50
--------------------------------
Column: sleep_hours
  Min: 2.5
  Max: 11.0
  Mean: 6.78
  Median: 6.80
--------------------------------
Column: pain_level
  Min: 0
  Max: 10
  Mean: 3.30
  Median: 3.00
--------------------------------
Column: blood_sugar_level
  Min: 65.0
  Max: 313.0
  Mean: 106.03
  Median: 102.90
--------------------------------
Column: heart_rate
  Min: 50.0
  Max: 120.0
  Mean: 83.10
  Median: 82.00
--------------------------------
Column: systolic_bp
  Min: 85.0
  Max: 193.0
  Mean: 123.50
  Median: 122.00
--------------------------------
Column: diastolic_bp
  Min: 55.0
  Max: 127.0
  Mean: 80.21
  Median: 80.00
--------------------------------
Dataset shape after validation:
(48121, 26)

Remaining Null Values:
record_id                0
patient_id               0
date                     0
weight_kg                0
meals_taken              0
meal_compliance          0
calorie_intake           0
protein_intake           0
carb_intake              0
fat_intake               0
water_intake_liters      0
steps_count              0
exercise_done            0
sleep_hours              0
symptoms                 0
pain_level               0
energy_level             0
mood_status              0
medication_taken         0
bowel_movement_status    0
blood_sugar_level        0
heart_rate               0
doctor_visit             0
notes                    0
systolic_bp              0
diastolic_bp             0
dtype: int64

**8. Save & Download the dataset**

In [ ]:
output_filename = "final_cleaned_tracking.csv"
df1.to_csv(output_filename, index=False)
files.download(output_filename)